export const INDUSTRY_JOB_MAP: Record<string, string[]> = {
    "Agriculture & Farming": ["Farm Manager", "Agronomist", "Field Supervisor", "Agricultural Technician", "Soil Scientist", "Irrigation Engineer"],
    "Animal & Livestock": ["Dairy Farm Manager", "Poultry Supervisor", "Veterinary Assistant", "Animal Feed Technician", "Fisheries Officer"],
    "Forestry & Logging": ["Forest Officer", "Timber Inspector", "Environmental Scientist"],
    "Mining & Extraction": ["Mining Engineer", "Geologist", "Safety Officer", "Drill Operator", "Mine Supervisor"],

    "Automobile & Auto Components": ["Production Engineer", "Quality Control Inspector", "Automotive Technician", "Dealer Sales Executive", "Service Advisor", "CNC Operator"],
    "Aerospace & Aviation": ["Aerospace Engineer", "Pilot", "Aircraft Technician", "Quality Inspector", "Logistics Coordinator"],
    "Shipbuilding": ["Marine Engineer", "Naval Architect", "Welder", "Production Supervisor"],
    "Railways & Locomotives": ["Locomotive Technician", "Track Engineer", "Station Manager", "Signal Technician"],
    "Industrial Machinery & Tools": ["Mechanical Engineer", "CNC Operator", "Maintenance Technician", "Design Engineer", "Production Supervisor"],
    "Heavy Engineering": ["Project Engineer", "Site Engineer", "Welder", "Fabrication Supervisor", "QA Engineer"],
    "Chemical & Petrochemical": ["Chemical Engineer", "Process Engineer", "Safety Officer", "Lab Chemist", "Production Supervisor", "EHS Manager"],
    "Pharmaceuticals": ["Medical Representative", "Regulatory Affairs Executive", "QA/QC Analyst", "Production Chemist", "R&D Scientist", "Sales Manager"],
    "Medical Devices & Equipment": ["Biomedical Engineer", "Service Engineer", "Sales Executive", "Quality Inspector", "R&D Engineer"],
    "Biotechnology": ["Biotechnologist", "Research Scientist", "Lab Analyst", "Regulatory Executive", "Production Executive"],
    "Ayurvedic / Herbal Manufacturing": ["Production Executive", "QA Analyst", "Regulatory Officer", "Sales Executive"],
    "Food & Beverage Manufacturing": ["Food Technologist", "Quality Controller", "Production Supervisor", "Plant Manager", "Packaging Engineer"],
    "Dairy Products": ["Dairy Technologist", "Quality Inspector", "Plant Operator", "Sales Executive"],
    "Packaged Food": ["Production Manager", "Food Safety Officer", "Sales Representative", "Quality Analyst"],
    "Edible Oils": ["Production Technician", "Chemical Analyst", "Quality Manager", "Sales Executive"],
    "Textiles & Apparel": ["Textile Engineer", "Garment Designer", "Merchandiser", "Quality Inspector", "Production Manager", "Cutting Master"],
    "Leather & Footwear": ["Leather Technician", "Product Designer", "Quality Inspector", "Production Supervisor"],
    "Electronics & Electricals": ["Electronics Engineer", "Hardware Engineer", "Production Supervisor", "Quality Inspector", "Service Engineer"],
    "Semiconductors": ["Process Engineer", "Design Engineer", "Quality Analyst", "R&D Engineer"],
    "Cables & Wires": ["Production Engineer", "Quality Inspector", "Sales Executive", "Plant Operator"],
    "Steel & Metals": ["Metallurgist", "Production Engineer", "Quality Inspector", "Safety Officer", "Plant Manager"],
    "Foundry & Casting": ["Foundry Engineer", "Production Incharge", "Quality Inspector", "Maintenance Technician"],
    "Plastics, Rubber & Polymers": ["Polymer Technologist", "Production Supervisor", "Quality Inspector", "Mould Operator"],
    "Glass & Ceramics": ["Production Engineer", "Quality Inspector", "Design Engineer", "Plant Manager"],
    "Construction Materials": ["Sales Executive", "Technical Executive", "Logistics Coordinator", "Plant Manager", "Quality Inspector"],
    "Packaging & Printing": ["Production Manager", "Design Executive", "Quality Inspector", "Sales Executive"],
    "Furniture & Woodwork": ["Furniture Designer", "Production Supervisor", "Sales Executive", "Carpenter", "Quality Inspector"],
    "Paints & Coatings": ["Chemical Engineer", "Sales Executive", "R&D Scientist", "Application Technician"],

    "Real Estate & Infrastructure": ["Real Estate Agent", "Site Engineer", "Project Manager", "Business Development Executive", "CRM Executive", "Sales Manager"],
    "Roads & Highways": ["Civil Engineer", "Project Manager", "Survey Engineer", "Site Supervisor"],
    "Architecture & Interior Design": ["Architect", "Interior Designer", "3D Visualizer", "CAD Designer", "Project Coordinator"],
    "Smart City & Urban Development": ["Urban Planner", "Civil Engineer", "Project Manager", "IoT Engineer"],

    "Information Technology (IT)": ["Software Developer", "Frontend Developer", "Backend Developer", "Full Stack Developer", "DevOps Engineer", "System Analyst", "IT Consultant"],
    "Software Development": ["Software Engineer", "Frontend Developer", "Backend Developer", "Full Stack Developer", "Mobile App Developer", "QA Engineer"],
    "Cloud Computing": ["Cloud Architect", "Cloud Engineer", "DevOps Engineer", "Solutions Architect"],
    "Cybersecurity": ["Security Analyst", "Ethical Hacker", "Security Engineer", "CISO", "SOC Analyst"],
    "Data Analytics & AI": ["Data Analyst", "Data Scientist", "ML Engineer", "Business Intelligence Analyst", "AI Researcher"],
    "Web & App Development": ["Web Developer", "Mobile App Developer", "UI/UX Designer", "Frontend Developer"],
    "BPO / KPO / Call Center": ["Customer Support Executive", "Team Leader", "Quality Analyst", "Operations Manager", "Process Executive"],
    "Telecom & Internet": ["Network Engineer", "Telecom Engineer", "RF Engineer", "Sales Executive", "Field Technician"],

    "Banking": ["Relationship Manager", "Branch Manager", "Credit Analyst", "Loan Officer", "Teller", "Sales Executive (CASA/HL/LAP/BL/SME)"],
    "NBFC & Microfinance": ["Loan Officer", "Credit Manager", "Field Executive", "Recovery Executive", "Branch Manager"],
    "Insurance (Life / General / Health)": ["Insurance Advisor", "Claims Manager", "Underwriter", "Sales Manager", "Branch Manager", "Actuarial Analyst"],
    "Investment & Wealth Management": ["Wealth Manager", "Investment Advisor", "Portfolio Manager", "Financial Analyst"],
    "Fintech & Payment Solutions": ["Product Manager", "Software Developer", "Business Analyst", "Sales Executive", "Compliance Officer"],
    "Stockbroking & Mutual Funds": ["Research Analyst", "Dealer", "Relationship Manager", "Compliance Officer"],

    "FMCG": ["Sales Executive", "Area Sales Manager", "Brand Manager", "Trade Marketing Executive", "Supply Chain Executive", "Key Account Manager"],
    "Retail": ["Store Manager", "Sales Associate", "Visual Merchandiser", "Customer Service Executive", "Inventory Manager"],
    "E-commerce": ["Category Manager", "Digital Marketing Executive", "Warehouse Supervisor", "Customer Support", "Operations Manager"],
    "Consumer Durables": ["Sales Executive", "Service Engineer", "Area Manager", "Product Manager"],
    "Fashion Retail": ["Store Manager", "Fashion Designer", "Merchandiser", "Visual Merchandiser", "Sales Associate"],
    "Beauty & Personal Care": ["Sales Executive", "Brand Executive", "Beauty Advisor", "Distribution Manager"],
    "Jewellery": ["Jewellery Designer", "Sales Executive", "Store Manager", "Quality Inspector"],

    "Logistics & Supply Chain": ["Logistics Coordinator", "Supply Chain Manager", "Warehouse Manager", "Fleet Manager", "Operations Executive"],
    "Transport & Fleet": ["Fleet Manager", "Transport Coordinator", "Driver", "Operations Manager", "Logistics Executive"],
    "Warehousing & Distribution": ["Warehouse Manager", "Inventory Manager", "Warehouse Supervisor", "Packing Supervisor"],
    "Freight & Cargo": ["Freight Executive", "Cargo Supervisor", "Operations Manager", "Documentation Executive"],
    "Import–Export": ["Export Manager", "Import Coordinator", "Customs Executive", "Documentation Officer"],
    "Cold Chain Logistics": ["Cold Chain Manager", "Refrigeration Technician", "Logistics Executive"],

    "Hotels & Resorts": ["Hotel Manager", "Front Desk Executive", "F&B Manager", "Executive Chef", "Housekeeping Supervisor", "Sales Manager"],
    "Restaurants & QSR": ["Restaurant Manager", "Chef", "Kitchen Supervisor", "Outlet Manager", "Cashier"],
    "Travel & Tourism": ["Travel Agent", "Tour Manager", "Operations Executive", "Sales Executive"],
    "Airlines & Cruises": ["Cabin Crew", "Ground Staff", "Operations Manager", "Sales Executive"],
    "Facility & Event Management": ["Facility Manager", "Event Coordinator", "Housekeeping Supervisor", "Security Manager"],

    "Hospitals & Clinics": ["Doctor", "Nurse", "Hospital Administrator", "Medical Receptionist", "Physiotherapist", "Lab Technician"],
    "Diagnostics & Pathology": ["Lab Technician", "Pathologist", "Radiologist", "Collection Center Manager"],
    "Wellness, Spa & Fitness": ["Fitness Trainer", "Yoga Instructor", "Spa Therapist", "Nutritionist", "Center Manager"],
    "Mental Health": ["Psychiatrist", "Psychologist", "Counselor", "Therapist"],

    "Schools & Colleges": ["Teacher", "Principal", "Vice Principal", "Professor", "Academic Coordinator"],
    "EdTech": ["Content Creator", "Instructional Designer", "Sales Executive", "Product Manager", "Tech Developer"],
    "Coaching & Skill Development": ["Trainer", "Coordinator", "Business Development Executive", "Center Head"],

    "Advertising & Digital Marketing": ["Digital Marketing Executive", "Social Media Manager", "SEO Specialist", "Content Writer", "Brand Manager", "Creative Designer"],
    "Media & Broadcasting": ["Journalist", "Content Producer", "Video Editor", "News Anchor", "Reporter"],
    "Film, OTT & Production": ["Director", "Producer", "Assistant Director", "Cinematographer", "Editor", "Production Assistant"],
    "Animation & Graphic Design": ["Graphic Designer", "Animator", "3D Artist", "Motion Designer", "UI/UX Designer"],
    "Gaming & Esports": ["Game Developer", "Game Designer", "QA Tester", "Community Manager", "Esports Manager"],

    "Legal Services": ["Lawyer", "Legal Advisor", "Legal Executive", "Compliance Officer", "Paralegal"],
    "CA & Accounting": ["Chartered Accountant", "Accountant", "Auditor", "Tax Consultant", "Finance Executive"],
    "Business Consulting": ["Management Consultant", "Strategy Analyst", "Business Analyst", "Operations Consultant"],
    "HR & Recruitment": ["HR Executive", "Recruiter", "HR Manager", "Payroll Executive", "Talent Acquisition"],
    "Market Research": ["Research Analyst", "Data Analyst", "Field Investigator", "Research Manager"],

    "Oil & Gas": ["Petroleum Engineer", "Geologist", "Drilling Engineer", "Operations Manager", "Safety Officer"],
    "Power & Electricity": ["Electrical Engineer", "Power Plant Operator", "Substation Engineer", "Maintenance Technician"],
    "Renewable Energy (Solar, Wind, Hydro)": ["Solar Engineer", "Wind Turbine Technician", "Project Manager", "Sales Executive", "Site Engineer"],

    "Electric Vehicles (EV)": ["EV Engineer", "Battery Technologist", "Sales Executive", "Software Developer", "R&D Engineer"],
    "IoT & Smart Devices": ["IoT Engineer", "Embedded Systems Engineer", "Product Manager", "Hardware Engineer"],
    "Blockchain & Crypto": ["Blockchain Developer", "Smart Contract Engineer", "Crypto Analyst", "Compliance Officer"],
    "R&D & Scientific Research": ["Research Scientist", "Lab Analyst", "R&D Manager", "Technical Writer"],
    "Robotics & Automation": ["Robotics Engineer", "Automation Engineer", "PLC Programmer", "Systems Integrator"],
    "Green Technology & Waste Management": ["Environmental Engineer", "Sustainability Manager", "Waste Management Executive"],

    "Government & Public Sector": ["Clerk", "Officer", "Administrative Executive", "IAS/IPS Aspirant", "PSU Engineer"],
    "Security Services": ["Security Guard", "Security Supervisor", "Security Manager", "Trainer"],
    "NGO & Social Sector": ["Program Manager", "Field Coordinator", "Social Worker", "Fundraising Executive"],
    "Freelancer / Self-Employed": ["Freelancer", "Consultant", "Self-Employed Professional"],
    "Other": ["Other"],
};
